name: CD (Deployment) Pipeline.

on:
  push:
    branches:
      - main

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: repo-basename
      run: |
        echo "value=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
      shell: bash
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      env:
        BASE_URL: /couch-supply/
      with:
        username: ${{ github.repository_owner }}
        reponame: ${{ steps.repo-basename.outputs.value }}
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
